#!/bin/bash

cd `dirname "$0"`

# Obfuscate the obfuscator as a torture test

../pyobfuscate ../pyobfuscate > pyobfuscate
chmod u+x pyobfuscate

for fn in test_*.py; do
	echo
	echo "@@ $fn @@"
	echo
	./pyobfuscate $fn | python -
done
